### ISSUE TITLE
Device initialisation

### ISSUE THREAD

**Issue by mazareth** [TheThingsNetwork/docs#176]
Hi,
I've a problem to add a device in my the things network account.
When a do that:
![image](https://user-images.githubusercontent.com/19725586/32842716-144b0542-ca1e-11e7-9029-fbe387694120.png)

I've this error:
![image](https://user-images.githubusercontent.com/19725586/32842613-d10c156e-ca1d-11e7-9b95-c8aa5a0a6bfd.png)

**Comment by johanstokking** [comment]
Hi @mazareth, this means that the AppEUI and DevEUI combination already exists.

We clarified the error message in a PR that is open / not yet deployed.

**Comment by mazareth** [comment]
but that's because my device is a finished product
I can't change these parameters
How can i add my smilio in "the thing network"? 

edit 
i try to add the demo-smiley app but an error occur

![image](https://user-images.githubusercontent.com/19725586/32843385-eb697de6-ca1f-11e7-9b8c-4c44022f556f.png)

**Comment by johanstokking** [comment]
Please contact the manufacturer in that case.

The problem is that it seems that application `demo-smiley` already exists with this device registered in it. You cannot take ownership of a AppEUI/DevEUI combination if it is already registered.

This will be solved when using LoRaWAN Join Servers, which is something I would recommend the manufacturer doing.

**Comment by mazareth** [comment]
Thanks johan,
I will contact the manufacturer.

Another solution could be to do a personal lora server?

**Comment by johanstokking** [comment]
Not really, because join requests may conflict then.

Manufacturers should not ship devices that can't change security settings and that are already registered with their AppEUI, DevEUI and AppKey combination.
