### ISSUE TITLE
ADR Documentation

### ISSUE THREAD

**Issue by maebli** [TheThingsNetwork/docs#267]
For me there are some unclear points in the ADR documentation:

*  "1. The initial ADR Request (for US915 and AU915)." does it only happen for these regions?
* "4. An ADR request is sent when the device sets the ADRAckReq bit" Always?
* "ADR requests are no longer scheduled or sent if the device refused several ADR requests" what does "refused" mean? The downlink is confirmed?
* Do ADRrequests only happen as piggy backs?

**Comment by htdvisser** [comment]
The initial ADR request is indeed only sent for those regions. In LoRaWAN 1.0.x the channels of those regions can't be configured with the CFList in the Join-Accept, and we have to work around that limitation by using the ADR mechanism.

The server must respond "soon" after it receives an uplink with the ADRAckReq set. We send the ADR request because we need to send a downlink (ACK) anyway; then we can just as well attach an ADR request to it.

Devices must respond to downlink MAC requests to inform the network server about whether the command succeeded or not. If (ADR) MAC commands fail too often, then we assume the device is broken and don't bother wasting more downlink on it.

In our current v2 implementation, MAC commands are preferably piggy-backed on existing downlinks (application downlink or ACK). Only if absolutely necessary, we initiate downlinks (for example, when devices are using slow data rates without reason).

**Comment by maebli** [comment]
Thanks
