### ISSUE TITLE
Document when a gateway's new location will take affect

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/docs#426]
I had a question about this. Maybe worth documenting. I can do this myself, but don't have time now. So just adding this ticket as a reminder.

> jpmeijers  6 minutes ago
> After setting a gateway's location on the V3 console, and making it public, how long should it take for the location to appear in the mqtt metadata?
> 
> htdvisser  2 minutes ago
> This definitely happens when the gateway reconnects
> 
> htdvisser  2 minutes ago
> I'm not sure if / how often it's refreshed while the gateway stays connected
> 
> jpmeijers  < 1 minute ago
> Ahh ok, then let me force reconnect the gateway

**Comment by ngalfas** [comment]
Hi, we deployed a public TTS v3 gateway for Kozani, Greece. We used ttnmapper app to check some uplinks from that GW.

After the initial mapping, I changed the physical location of the gateway, its new location is several kilometers away from the old location. I also changed the location on TTS console because the GW has no GPS on it. So i was waiting to see the location on ttnmapper to change. 
This didn't happen even after two days passed and signals keep coming. ttnmapper shows the old location.

After a hint from jpmeijers i can confirm that the change of GW location at the TTS console does not reflect on change of the location in the next downlinks JSON from that GW. They still include the old location. 
Seems a restart of the GW is needed!
